/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.51
 * Generated at: 2018-05-19 09:36:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Register</title>\r\n");
      out.write("<script> \r\n");
      out.write("function validate()\r\n");
      out.write("{ \r\n");
      out.write("\t var fullname = document.form.fullname.value;\r\n");
      out.write(" \tvar email = document.form.email.value;\r\n");
      out.write(" \tvar username = document.form.username.value; \r\n");
      out.write(" \tvar password = document.form.password.value;\r\n");
      out.write(" \tvar conpassword= document.form.conpassword.value;\r\n");
      out.write(" \r\n");
      out.write(" \tif (fullname==null || fullname==\"\")\r\n");
      out.write("\t { \r\n");
      out.write("\t\t alert(\"Full Name can't be blank\"); \r\n");
      out.write(" \t\treturn false; \r\n");
      out.write(" \t}\r\n");
      out.write(" \telse if (email==null || email==\"\")\r\n");
      out.write(" \t{ \r\n");
      out.write(" \t\talert(\"Email can't be blank\"); \r\n");
      out.write(" \t\treturn false; \r\n");
      out.write(" \t}\r\n");
      out.write(" \telse if (username==null || username==\"\")\r\n");
      out.write(" \t{ \r\n");
      out.write(" \talert(\"Username can't be blank\"); \r\n");
      out.write("\t return false; \r\n");
      out.write(" \t}\r\n");
      out.write(" \telse if(password.length<6)\r\n");
      out.write(" \t{ \r\n");
      out.write(" \t\talert(\"Password must be at least 6 characters long.\"); \r\n");
      out.write(" \treturn false; \r\n");
      out.write("\t } \r\n");
      out.write("\t else if (password!=conpassword)\r\n");
      out.write("\t { \r\n");
      out.write(" \t\talert(\"Confirm Password should match with the Password\"); \r\n");
      out.write(" \t\treturn false; \r\n");
      out.write("\t } \r\n");
      out.write(" } \r\n");
      out.write("</script> \r\n");
      out.write("<link rel = \"stylesheet\" type = \"text/css\" href = \"registration.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center><h2>Online Gaming Site Registration</h2></center>\r\n");
      out.write("<form name=\"form\" action=\"RegisterServlet\" method=\"post\" onsubmit=\"return validate()\">\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>Full Name</td>\r\n");
      out.write(" <td><input type=\"text\" name=\"fullname\" /></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>Email</td>\r\n");
      out.write(" <td><input type=\"text\" name=\"email\" /></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>Username</td>\r\n");
      out.write(" <td><input type=\"text\" name=\"username\" /></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>Password</td>\r\n");
      out.write(" <td><input type=\"password\" name=\"password\" /></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>Confirm Password</td>\r\n");
      out.write(" <td><input type=\"password\" name=\"conpassword\" /></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>");
      out.print((request.getAttribute("errMessage") == null) ? "": request.getAttribute("errMessage"));
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>Already Registered..Log in here<a href=\"login.jsp\"> LOG IN</a></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td></td>\r\n");
      out.write(" <td><input type=\"submit\" value=\"Register\"></input></td>\r\n");
      out.write(" </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
