/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.51
 * Generated at: 2018-05-19 09:50:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcomepAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Ex Games</title>\r\n");
      out.write("<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--[if IE 6]><link rel=\"stylesheet\" href=\"css/ie6-style.css\" type=\"text/css\" media=\"all\" /><![endif]-->\r\n");
      out.write("<script src=\"js/jquery-1.3.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/fns.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Page -->\r\n");
      out.write("<div id=\"page\" class=\"shell\">\r\n");
      out.write("  <!-- Header -->\r\n");
      out.write("  <div id=\"header\">\r\n");
      out.write("    <!-- Top Navigation -->\r\n");
      out.write("    <div id=\"top-nav\">\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / Top Navigation -->\r\n");
      out.write("    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("    <!-- Logo -->\r\n");
      out.write("    <div id=\"logo\">\r\n");
      out.write("      <h1><a href=\"#\">Ex<span>GAMES</span></a></h1>\r\n");
      out.write("      <p class=\"description\">Challenge Everything</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / Logo -->\r\n");
      out.write("    <!-- Main Navigation -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- / Main Navigation -->\r\n");
      out.write("    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("    <!-- Sort Navigation -->\r\n");
      out.write("    <div id=\"sort-nav\">\r\n");
      out.write("      <div class=\"bg-right\">\r\n");
      out.write("        <div class=\"bg-left\">\r\n");
      out.write("          <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"first active first-active\"><a href=\"#\">Review</a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("            <li><a href=\"article.jsp\">Latest Articles </a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("            <li><a href=\"searchView.jsp\"><form method = \"post\" action =\"searchAll \" >New Releases</form></a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("            <li><a href=\"GameServlet\" method =\"post\">All Games</a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("            <li><a href=\"addGames.jsp\">Add Games </a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("\t\t\t<li><a href=\"LogOutServlet\">Log out</a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / Sort Navigation -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- / Header -->\r\n");
      out.write("  <!-- Main -->\r\n");
      out.write("  <div id=\"main\">\r\n");
      out.write("    <div id=\"main-bot\">\r\n");
      out.write("      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("      <!-- Content -->\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("        <div class=\"block\">\r\n");
      out.write("          <div class=\"block-bot\">\r\n");
      out.write("            <div class=\"block-cnt\">\r\n");
      out.write("              <div id=\"slider\">\r\n");
      out.write("                <div class=\"buttons\"> <span class=\"prev\">prev</span> <span class=\"next\">next</span> </div>\r\n");
      out.write("                <div class=\"holder\">\r\n");
      out.write("                  <div class=\"frame\">&nbsp;</div>\r\n");
      out.write("                  <div class=\"content\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                    <li class=\"fragment\">\r\n");
      out.write("                      <div class=\"image\">\r\n");
      out.write("                      <img src=\"css/images/nfs2.jpg\" alt=\"\" height=\"290px\" width=\"700px\" /> \r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"cnt\">\r\n");
      out.write("                    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                    <div class=\"side-a\">\r\n");
      out.write("                      <h4>NFS</h4>\r\n");
      out.write("                      <ul class=\"rating\">\r\n");
      out.write("                        <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"votes\">2.325 votes</span></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"side-b\">\r\n");
      out.write("                      <p>Need for Speed: Most Wanted is a 2005 racing video game developed by EA Black Box and published by Electronic Arts. It is the ninth installment in the Need for Speed series. </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"fragment\">\r\n");
      out.write("                    <div class=\"image\"> <img src=\"css/images/gta.jpg\" alt=\"\"height=\"290px\" width=\"700px\" /> </div>\r\n");
      out.write("                    <div class=\"cnt\">\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                      <div class=\"side-a\">\r\n");
      out.write("                        <h4>GTA 4</h4>\r\n");
      out.write("                        <ul class=\"rating\">\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"votes\">0.523 votes</span></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"side-b\">\r\n");
      out.write("                        <p>Grand Theft Auto IV is an action-adventure video game developed by Rockstar North and published by Rockstar Games. It was released for the PlayStation 3 and Xbox 360 consoles on 29 April 2008, and for Microsoft Windows on 2 December 2008..</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"fragment\">\r\n");
      out.write("                    <div class=\"image\"> <img src=\"css/images/maxresdefault.jpg\" alt=\"\"height=\"290px\" width=\"700px\" /> </div>\r\n");
      out.write("                    <div class=\"cnt\">\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                      <div class=\"side-a\">\r\n");
      out.write("                        <h4>IGI</h4>\r\n");
      out.write("                        <ul class=\"rating\">\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"votes\">1.456 votes</span></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"side-b\">\r\n");
      out.write("                        <p>Project I.G.I.: I'm Going In is a tactical first-person shooter video game developed by Innerloop Studios and released on December 15, 2000 by Eidos Interactive.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"fragment\">\r\n");
      out.write("                    <div class=\"image\"> <img src=\"css/images/spiderman_sg.jpg\" alt=\"\"height=\"290px\" width=\"700px\" /> </div>\r\n");
      out.write("                    <div class=\"cnt\">\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                      <div class=\"side-a\">\r\n");
      out.write("                        <h4>Spider Man</h4>\r\n");
      out.write("                        <ul class=\"rating\">\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"votes\">3.456 votes</span></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"side-b\">\r\n");
      out.write("                        <p>Spider-Man is an upcoming action-adventure game based on the Marvel Comics superhero Spider-Man, developed by Insomniac Games and published by Sony Interactive Entertainment for PlayStation 4.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"head\">\r\n");
      out.write("            <div class=\"head-cnt\"> <a href=\"#\" class=\"view-all\">view all</a>\r\n");
      out.write("              <h3>Top Reviews</h3>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-articles articles\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/3max.jpg\" alt=\"\"height=\"99px\" width=\"194px\" /></a> </div>\r\n");
      out.write("              <h4><a href=\"#\">INJUSTICE 2</a></h4>\r\n");
      out.write("              <p class=\"console\"><strong>PS4</strong></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/clash-royale-1024x576.jpg\" alt=\"\"height=\"99px\" width=\"194px\" /></a> </div>\r\n");
      out.write("              <h4><a href=\"#\">CLASH ROYALE</a></h4>\r\n");
      out.write("              <p class=\"console\"><strong>PC</strong></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/Dota2Logo.jpg\" alt=\"\"height=\"99px\" width=\"194px\" /></a> </div>\r\n");
      out.write("              <h4><a href=\"#\">DOTA 2</a></h4>\r\n");
      out.write("              <p class=\"console\"><strong>PC</strong></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("       <div class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"head\">\r\n");
      out.write("            <div class=\"head-cnt\"> <a href=\"#\" class=\"view-all\">view all</a>\r\n");
      out.write("              <h3>Free Pc Games</h3>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"row-articles articles\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/StarCraft_box_art.jpg\" alt=\"\" height=\"120px\" width=\"194px\"/></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">StarCraft</a></h4>\r\n");
      out.write("                <p>Two decades after it was first released, Blizzard now offers its strategy space opera free of charge. The bundle also brings you the Brood War expansionâs fresh crop of campaigns, tilesets, units and upgrade advancement. One of the longest-serving games on the esports circuit, the pro scene is largely over for StarCraft, but the top players can still make a few bob in the tournaments that remain. That means in addition to being a free game, you could pump up your actions-per-minute and earn an infinite return on your zero investment </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/StickShift.jpg\" alt=\"\"height=\"120px\" width=\"194px\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">Stick Shift</a></h4>\r\n");
      out.write("                <p>As creator Robert Yang says, âStick Shift is an autoerotic night-driving game about pleasuring a gay car.â Itâs part of an anthology with Hurt Me Plenty and Succulent, covering eroticism, politics and more. Stick Shift is funny while also offering food for thought..</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article last-article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/Harry-Potter-Collection-PC-600x300.jpg\" alt=\"\"height=\"120px\" width=\"194px\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">Harry Potter</a></h4>\r\n");
      out.write("                <p>With the film series about to conclude in 2010, LEGO re-acquired rights on the Harry Potter series and, together with its new toy sets, planned the release of a remastered video game based on the Harry Potter series. Traveller's Tales (TT) then produced LEGO Harry Potter: Years 1-4, as part of the LEGO video game series. Focusing on the first four years in the Harry Potter series, the game featured a very detailed and consistent gameplay, in addition to the original soundtrack used in the films.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / Content -->\r\n");
      out.write("    <!--  -->\r\n");
      out.write("    <div id=\"sidebar\">\r\n");
      out.write("      <!-- Search -->\r\n");
      out.write("      <div id=\"search\" class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"block-cnt\">\r\n");
      out.write("             <form method = \"post\" action =\"search \">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"fieldplace\">\r\n");
      out.write("                 <input type=\"text\" class=\"field\" placeholder=\"search\" name=\"gamename\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <input type=\"submit\" class=\"button\" value=\"GO\" />\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- / Search -->\r\n");
      out.write("      <!-- Sign In -->\r\n");
      out.write("      <div id=\"sign\" class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"block-cnt\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- / Sign In -->\r\n");
      out.write("      <div class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"head\">\r\n");
      out.write("            <div class=\"head-cnt\">\r\n");
      out.write("              <h3>Top Games</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"image-articles articles\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/7183jraRBfL._SY445_.jpg\" alt=\"\"height=\"120px\" width=\"51px\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">BATMAN</a></h4>\r\n");
      out.write("                <p>Batman: Arkham is a series of action-adventure video games based on the DC Comics character Batman, developed by Rocksteady Studios and WB Games MontrÃ©al, and published by Warner Bros. Interactive Entertainment. </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/51AMFFS7WQL._SY445_.jpg\" alt=\"\"height=\"120px\" width=\"51px\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">CALL OF DUTY</a></h4>\r\n");
      out.write("                <p>Call of Duty is a first-person shooter video game franchise. The series began on Microsoft Windows, and later expanded to consoles and handhelds. Several spin-off games have been released </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/Princeofpersia4TheSandsofTimeCover-1.jpg\" alt=\"\" height=\"120px\" width=\"51px\"/></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">PRINCE OF PERCIA</a></h4>\r\n");
      out.write("                <p>Prince of Persia is an action-adventure and platforming video game developed by Ubisoft Montreal and published by Ubisoft. It is part of the Prince of Persia franchise. </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <a href=\"#\" class=\"view-all\">view all</a>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"head\">\r\n");
      out.write("            <div class=\"head-cnt\">\r\n");
      out.write("              <h3>Top Videos</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"image-articles articles\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/gta-vice-city-pc-game-500x500.jpg\" alt=\"\"height=\"120px\" width=\"51px\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">Vice City</a></h4>\r\n");
      out.write("                <p>Grand Theft Auto: Vice City is an action-adventure video game developed by Rockstar North and published by Rockstar Games </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/Iron-Man-PC-Free-Download.jpg\" alt=\"\" height=\"100px\" width=\"51px\"/></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">Iron Man</a></h4>\r\n");
      out.write("                <p>Iron Man is an action-adventure video game based on the film of the same name as well as the classic iterations of the character. It was released on May 2, 2008 to coincide with the release of the film in cinemas. </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"css/images/images.jpg\" alt=\"\" height=\"100px\" width=\"51px\"/></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">Delta Force</a></h4>\r\n");
      out.write("                <p>Delta Force is a tactical first-person shooter computer game by developer and publisher NovaLogic. It was released for Microsoft Windows in 1998, and re-released on Steam in 2009 </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <a href=\"#\" class=\"view-all\">view all</a>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    <!-- / Sidebar -->\r\n");
      out.write("    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("      <div class=\"navs\">\r\n");
      out.write("        <div class=\"navs-bot\">\r\n");
      out.write("          <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">community</a></li>\r\n");
      out.write("            <li><a href=\"#\">forum</a></li>\r\n");
      out.write("            <li><a href=\"#\">video</a></li>\r\n");
      out.write("            <li><a href=\"#\">cheats</a></li>\r\n");
      out.write("            <li><a href=\"#\">features</a></li>\r\n");
      out.write("            <li><a href=\"#\">downloads</a></li>\r\n");
      out.write("            <li><a href=\"#\">sports</a></li>\r\n");
      out.write("            <li><a href=\"#\">tech</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">pc</a></li>\r\n");
      out.write("            <li><a href=\"#\">xbox</a></li>\r\n");
      out.write("            <li><a href=\"#\">360</a></li>\r\n");
      out.write("            <li><a href=\"#\">wii</a></li>\r\n");
      out.write("            <li><a href=\"#\">ps3</a></li>\r\n");
      out.write("            <li><a href=\"#\">ps2</a></li>\r\n");
      out.write("            <li><a href=\"#\">psp</a></li>\r\n");
      out.write("            <li><a href=\"#\">ds</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("     <p class=\"copy\">SLIIT 2nd year group project_GROUP NO 61 </p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / Main -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / Page -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
