/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.51
 * Generated at: 2018-05-17 10:40:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcomeAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Game</title>\r\n");
      out.write("<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"welcome1.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--[if IE 6]><link rel=\"stylesheet\" href=\"welcome2.css\" type=\"text/css\" media=\"all\" /><![endif]-->\r\n");
      out.write("<script src=\"js/jquery-1.3.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/fns.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Page -->\r\n");
      out.write("<div id=\"page\" class=\"shell\">\r\n");
      out.write("  <!-- Header -->\r\n");
      out.write("  <div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("    <!-- Logo -->\r\n");
      out.write("    <div id=\"logo\">\r\n");
      out.write("      <h1><a href=\"#\">Mini<span>Games</span></a></h1>\r\n");
      out.write("      <p class=\"description\">your game zone</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / Logo -->\r\n");
      out.write("\r\n");
      out.write("    <!-- / Main Navigation -->\r\n");
      out.write("    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("    <!-- Sort Navigation -->\r\n");
      out.write("    <div id=\"sort-nav\">\r\n");
      out.write("      <div class=\"bg-right\">\r\n");
      out.write("        <div class=\"bg-left\">\r\n");
      out.write("          <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"first active first-active\"><a href=\"#\">Review</a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("            <li><a href=\"article.jsp\">Latest Articles </a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("            <li><a href=\"searchView.jsp\"><form method = \"POST\" action =\"searchAll \" >New Releases</form></a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("            <li><a href=\"GameServlet\" method =\"post\">All Games</a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("              <li><a href=\"addGames.jsp\">Add Games </a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("\t\t\t<li><a href=\"LogOutServlet\">Log out</a><span class=\"sep\">&nbsp;</span></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / Sort Navigation -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- / Header -->\r\n");
      out.write("  <!-- Main -->\r\n");
      out.write("  <div id=\"main\">\r\n");
      out.write("    <div id=\"main-bot\">\r\n");
      out.write("      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("      <!-- Content -->\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("        <div class=\"block\">\r\n");
      out.write("          <div class=\"block-bot\">\r\n");
      out.write("            <div class=\"block-cnt\">\r\n");
      out.write("              <div id=\"slider\">\r\n");
      out.write("                <div class=\"buttons\"> <span class=\"prev\">prev</span> <span class=\"next\">next</span> </div>\r\n");
      out.write("                <div class=\"holder\">\r\n");
      out.write("                  <div class=\"frame\">&nbsp;</div>\r\n");
      out.write("                  <div class=\"content\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                    <li class=\"fragment\">\r\n");
      out.write("                      <div class=\"image\">\r\n");
      out.write("                      <img src=\"images/img10.jpg\" alt=\"\" /> \r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"cnt\">\r\n");
      out.write("                    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                    <div class=\"side-a\">\r\n");
      out.write("                      <a href=\"downloadStarcraft.jsp\"><h4>StarCraft II</h4></a>\r\n");
      out.write("                      <ul class=\"rating\">\r\n");
      out.write("                        <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                        <li><span class=\"votes\">1.456 votes</span></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"side-b\">\r\n");
      out.write("                      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condi- mentum. Suspendisse gravida elementum mauris, in vulputate justo ultrices sit amet.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"fragment\">\r\n");
      out.write("                    <div class=\"image\"> <img src=\"images/img10.jpg\" alt=\"\" /> </div>\r\n");
      out.write("                    <div class=\"cnt\">\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                      <div class=\"side-a\">\r\n");
      out.write("                        <a href=\"downloadStarcraft.jsp\"><h4>StarCraft II</h4></a>\r\n");
      out.write("                        <ul class=\"rating\">\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"votes\">1.456 votes</span></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"side-b\">\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condi- mentum. Suspendisse gravida elementum mauris, in vulputate justo ultrices sit amet.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"fragment\">\r\n");
      out.write("                    <div class=\"image\"><img src=\"images/img10.jpg\" alt=\"\" ></div>\r\n");
      out.write("                    <div class=\"cnt\">\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                      <div class=\"side-a\">\r\n");
      out.write("                        <h4>StarCraft II</h4>\r\n");
      out.write("                        <ul class=\"rating\">\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"votes\">1.456 votes</span></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"side-b\">\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condi- mentum. Suspendisse gravida elementum mauris, in vulputate justo ultrices sit amet.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"fragment\">\r\n");
      out.write("                    <div class=\"image\"> <img src=\"images/img10.jpg\" alt=\"\" /> </div>\r\n");
      out.write("                    <div class=\"cnt\">\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                      <div class=\"side-a\">\r\n");
      out.write("                        <h4>StarCraft II</h4>\r\n");
      out.write("                        <ul class=\"rating\">\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star full-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"star empty-star\">&nbsp;</span></li>\r\n");
      out.write("                          <li><span class=\"votes\">1.456 votes</span></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"side-b\">\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condi- mentum. Suspendisse gravida elementum mauris, in vulputate justo ultrices sit amet.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"head\">\r\n");
      out.write("            <div class=\"head-cnt\"> <a href=\"#\" class=\"view-all\">view all</a>\r\n");
      out.write("              <h3>Top Reviews</h3>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-articles articles\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"images/img4.jpg\" alt=\"\" /></a> </div>\r\n");
      out.write("              <h4><a href=\"downloadfear.jsp\">FEAR 2</a></h4>\r\n");
      out.write("              <p class=\"console\"><strong>PSP3</strong></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"image\"> <a href=\"downloadfallout.jsp\"><img src=\"images/img5.jpg\" alt=\"\" /></a> </div>\r\n");
      out.write("              <h4><a href=\"downloadfear.jsp\">FALLOUT 3</a></h4>\r\n");
      out.write("              <p class=\"console\"><strong>PC</strong></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"images/img6.jpg\" alt=\"\" /></a> </div>\r\n");
      out.write("              <h4><a href=\"downloadStarcraft.jsp\">STARCRAF II</a></h4>\r\n");
      out.write("              <p class=\"console\"><strong>PC</strong></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"head\">\r\n");
      out.write("            <div class=\"head-cnt\"> <a href=\"#\" class=\"view-all\">view all</a>\r\n");
      out.write("              <h3>Editor`s Pick</h3>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"row-articles articles\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"downloadfear.jsp\"><img src=\"images\\img7.jpg\" alt=\"\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"downloadfear.jsp\">F.E.A.R.2</a></h4>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condimentum. Suspendisse gravida elementum mauris, in vulputate justo ultrices sit amet. Maecenas ultricies elit </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"downloadfear.jsp\"><img src=\"images/img8.jpg\" alt=\"\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"downloadfear.jsp\">FALLOUT 3</a></h4>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condimentum. Suspendisse gravida elementum mauris, in vulputate justo ultrices sit amet. Maecenas ultricies elit in mi sagittis fringilla.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article last-article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"downloadStarcraft.jsp\"><img src=\"images/img9.jpg\" alt=\"\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"downloadStarcraft.jsp\">STARCRAF II</a></h4>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condimentum. Suspendisse gravida elementum mauris, in vulputate justo ultrices sit amet. Maecenas ultricies elit in mi sagittis fringilla.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / Content -->\r\n");
      out.write("    <!--  -->\r\n");
      out.write("    <div id=\"sidebar\">\r\n");
      out.write("      <!-- Search -->\r\n");
      out.write("      <div id=\"search\" class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"block-cnt\">\r\n");
      out.write("            <form method = \"POST\" action =\"search \" >\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"fieldplace\">\r\n");
      out.write("                <input type=\"text\" class=\"field\" placeholder=\"search\" name=\"name\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <input type=\"submit\"  class=\"button\" value=\"GO\"  />\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- / Search -->\r\n");
      out.write("      <!-- Sign In -->\r\n");
      out.write("      <div id=\"sign\" class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"block-cnt\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <!--<p class=\"center\"><a href=\"#\">Help?</a>&nbsp;&nbsp;<a href=\"#\">Forgot Password?</a></p>-->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- / Sign In -->\r\n");
      out.write("      <div class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"head\">\r\n");
      out.write("            <div class=\"head-cnt\">\r\n");
      out.write("              <h3>Top Games</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"image-articles articles\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"images/img1.gif\" alt=\"\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">TMNT</a></h4>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"images/img2.gif\" alt=\"\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">F.E.A.R.2</a></h4>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"images/img3.gif\" alt=\"\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">Steel Fury</a></h4>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <a href=\"#\" class=\"view-all\">view all</a>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"head\">\r\n");
      out.write("            <div class=\"head-cnt\">\r\n");
      out.write("              <h3>Top Videos</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"image-articles articles\">\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"images/img1.gif\" alt=\"\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">FALLOUT3</a></h4>\r\n");
      out.write("                <p>Fallout 3 is a post-apocalyptic action role-playing open world video game developed by Bethesda Game Studios </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"images/img2.gif\" alt=\"\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                <h4><a href=\"#\">Crysis</a></h4>\r\n");
      out.write("                <p>Crysis is a first-person shooter video game developed by Crytek and published by Electronic Arts for Microsoft Windows </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("              <div class=\"image\"> <a href=\"#\"><img src=\"images/img3.gif\" alt=\"\" /></a> </div>\r\n");
      out.write("              <div class=\"cnt\">\r\n");
      out.write("                 <h4><a href=\"#\">F.E.A.R.2</a></h4> \r\n");
      out.write("                <p>F.E.A.R. 2: Project Origin is a first-person shooter survival horror video game, developed by Monolith Productions and published by Warner Bros.  </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <a href=\"#\" class=\"view-all\">view all</a>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"block\">\r\n");
      out.write("        <div class=\"block-bot\">\r\n");
      out.write("          <div class=\"head\">\r\n");
      out.write("            <div class=\"head-cnt\">\r\n");
      out.write("              <h3>Latest Articles</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"text-articles articles\">\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <h4><a href=\"#\">Dolor amet sodales leo</a></h4>\r\n");
      out.write("              <small class=\"date\">21.07.09</small>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scele- risque leo sodales sit amet</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <h4><a href=\"#\">Amet sed lorem sit</a></h4>\r\n");
      out.write("              <small class=\"date\">20.07.09</small>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <h4><a href=\"#\">Adipsicing elit elementum</a></h4>\r\n");
      out.write("              <small class=\"date\">19.07.09</small>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"article\">\r\n");
      out.write("              <h4><a href=\"#\">Consectetur elit sed molestie</a></h4>\r\n");
      out.write("              <small class=\"date\">15.07.09</small>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("            <a href=\"#\" class=\"view-all\">view all</a>\r\n");
      out.write("            <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / Sidebar -->\r\n");
      out.write("    <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("      <div class=\"navs\">\r\n");
      out.write("        <div class=\"navs-bot\">\r\n");
      out.write("           <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("          </ul> \r\n");
      out.write("          <div class=\"cl\">&nbsp;</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <p class=\"copy\">SLIIT 2nd year group project_GROUP NO 61 </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / Footer -->\r\n");
      out.write("  </div></div>\r\n");
      out.write("<!-- / Main -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / Page -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
